name: isa
favicon: null
layout_spectrum: 0.30132093117572367
typography_spectrum: 0.3777782251127064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.048820019932463765
  lightness: 0.22638062853366137
  saturation: 0.15633949195034802
  rhythmicContrast: 0.6832214409951121
purpose: []
